### ISSUE TITLE
checkout (<target branch>): Fetch failed, error: exit status 128

### ISSUE THREAD

**Issue by freesatnaresh** [bitrise-steplib/steps-git-clone#108]
Hello all,

I am seeing some strange behaviour with git-clone step.

When I try to build an app on Bitraise, I am getting the fetch failed error during the git clone.

This existing app and workflows were defined by someone else.

I have created a new app and copied the workflows from the above existing app and I can build the app successfully.

Both apps are pointing to same git repo and on same branch I am seeing this different behaviour.

Any idea what could be causing this?

Log

| id: git-clone                                                                |
| version: 4.0.18                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-05-27T20:24:49Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
config:
- RepositoryURL: git@github.com:<repo>.git
- CloneIntoDir: /Users/vagrant/git
- Commit: 
- Tag: 
- Branch: <target-branch>
- BranchDest: 
- PRID: 0
- PRRepositoryURL: 
- PRMergeBranch: 
- ResetRepository: false
- CloneDepth: 0
- BuildURL: https://app.bitrise.io/build/0dce31d8725ea508
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
git "init"
Initialized empty Git repository in /Users/vagrant/git/.git/
git "remote" "add" "origin" "git@github.com:<repo>.git"
git "fetch" "origin" "<target-branch>"
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Attempt 1 failed:
exit status 128_

Thanks

**Comment by danielaraujorn** [comment]
same for me

**Comment by mediaController** [comment]
same for me

**Comment by androideveloper** [comment]
Any ideas? Started happening since today, but nothing changed for repo since yesterday

**Comment by bitce** [comment]
Hey everyone! Can you please verify that your SSH key is up and running on both the git and Bitrise end? In fact I'd just recommend generating a new keypair via Bitrise to make sure.

**Comment by androideveloper** [comment]
@bitce That's what we did to fix ti. Thanks

**Comment by nowele-rechka-entercom** [comment]
If setting up new SSH keys isn't fixing this, what else could be the issue?

**Comment by non-binary** [comment]
@nowele-rechka-entercom Does that mean you no longer require assistance?

**Comment by nowele-rechka-entercom** [comment]
> @nowele-rechka-entercom Does that mean you no longer require assistance?

I no longer require assistance now that builds are able to move past this step, but I'm wondering if there's anyway to get some insight into why the SSH key needed to be replaced? The previous key had not been adjusted and had worked fine for at least the past year. I joined the project after it had initially been setup but as far as I know it has historically been the only key until I generated new ones through Bitrise.

**Comment by bitce** [comment]
Hi @nowele-rechka-entercom!

Unfortunately, there is virtually no way to check why the previous key became invalid. In most cases this is done by minor changes on the git service end, like user or repo owner role changes, renaming apps or the organization, etc.

**Comment by nowele-rechka-entercom** [comment]
> Hi @nowele-rechka-entercom!
> 
> Unfortunately, there is virtually no way to check why the previous key became invalid. In most cases this is done by minor changes on the git service end, like user or repo owner role changes, renaming apps or the organization, etc.

Totally understandable! I just wanted to check if there was any potential issue from this step that could have caused it somehow. Thank you!

**Comment by godrei** [comment]
I'll close this issue, as it seems refreshing the ssh key solved the problem, but if you need more info/help just let us know by opening a new one!
