### ISSUE TITLE
Error: exit status 128 with git-clone@4.0.21 

### ISSUE THREAD

**Issue by emans** [bitrise-steplib/steps-git-clone#118]
Hello I am getting the error "Exit status 128", fatal: reference is not a tree. 

From the logs:

git "checkout" "6a02fas4d53a4d2f415e733565e4c09a1fddcb25"
fatal: reference is not a tree: 6a02fas4d53a4d2f415e733565e4c09a1fddcb25
ERROR: checkout (6a02fas4d53a4d2f415e733565e4c09a1fddcb25): checkout failed (6a02fas4d53a4d2f415e733565e4c09a1fddcb25), error: exit status 128

I use the integration with Gitlab available under the "account settings"

The last working version was 4.0.18. 

Can you help? Or how can I provide you more information? 

Regards.

**Comment by chaitanyatanna-bitrise** [comment]
Hi @emans 
Thank you for reaching out to Bitrise Support.
I want to let you know that our engineers are looking into this issue.
We will let you know the update soon.

Thanks
Chaitanya

**Comment by mjones-droid** [comment]
HI @emans. Please try increasing the clone depth on the git-clone step to 10 or possibly 50 and see if that resolves the issue.

**Comment by mjones-droid** [comment]
Hi @emans. This is a known issue. We have filed a bug report with the devs.

**Comment by emans** [comment]
@mjones-droid hi, thanks for help before everything.

so I did what you suggested with the clone depth and it worked. it fails first then it works.

First the error:

```
git "checkout" "8c225e4d6f30c7a1c112ce0faa6e043943247336"
fatal: reference is not a tree: 8c225e4d6f30c7a1c112ce0faa6e043943247336
Checkout failed, error: exit status 128

```
Then with the depth:

```
Unshallow...
git "fetch" "--unshallow"
```

Thanks for the help. If I can help somehow tell me or PM me :) 
Regards.

**Comment by godrei** [comment]
I'll close this issue, as it seems to be solved, but if you need more info/help just let us know by opening a new one!
