### ISSUE TITLE
4.2.0 broke git-submodule step

### ISSUE THREAD

**Issue by laco-dev** [bitrise-steplib/steps-git-clone#147]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.2.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

We use git-clone 4.x.x version with submodules and CI was failed from yesterday. I found that it was occurred only 4.2.0 version.
so i downgrade 4.1.0 and succeed it

### Bitrise info

- Build URL:  https://app.bitrise.io/build/83ab16ecae5a1f8c#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log:  It is private repo so i hidden some information.

<details>
  <pre>
 $ git "submodule" "update" "--init" "--recursive" "--depth=1"
Submodule ...
Cloning into ...
Warning: Permanently added the RSA host [REDACTED] for IP address '140.82.113.3' to the list of known hosts.
fatal: reference is not a tree: "hash"
Unable to checkout "hash" in submodule path '...'
ERROR: submodule update: 
Warning: Permanently added the RSA host [REDACTED] for IP address '140.82.113.3' to the list of known hosts.
fatal: reference is not a tree: "hash"
Unable to checkout "hash' in submodule path '...'
  </pre>
</details>

### Steps to reproduce

1. Use git-clone version to 4.x.x --> 4.2.0
2. Run any build
3. Get sub-modules

**Comment by kmityakov** [comment]
+1 Have the same issue here, downgrading to 4.1.0 fixes it

**Comment by marcosholgado** [comment]
+1 Setting shallow cloning for submodules to false also fixed that for us. I believed this could be related with https://github.com/bitrise-steplib/steps-git-clone/pull/143

**Comment by istvankovacs-bitrise** [comment]
Many thanks for reporting! We will take a look into it but in the meantime, please set the `Shallow update submodules` option of the Step (introduced in v4.2.0) to `false`, in order to disable the shallow cloning for the submodule.

**Comment by lpusok** [comment]
@laco-dev @kmityakov @marcosholgado Identified that the issue most likely is caused by the older git CLI version included on the Ubuntu 16.04 stack. If possible, please update to the Ubuntu 20.04 stack.

**Comment by marcosholgado** [comment]
@lpusok thanks, that did the trick 👍

**Comment by MapleSimon** [comment]
I was facing the same issue and updating to Ubuntu 20.04 resolved it.

If this can be any help, I found out the `$ git "submodule" "update" "--init" "--recursive" "--depth=1"` step isn't cloning in any path depth when our root `.gitmodules` includes a `.gitmodules` of its own specifying a deeper path.

**16.04**
```
Submodule 'Assets/ExampleSDK' (https://github.com/[REDACTED]/ExampleSDK.git) registered for path 'Assets/ExampleSDK'
Cloning into 'Assets/ExampleSDK'...
```
vs

**20.04**
```
Submodule 'Assets/ExampleSDK' (https://github.com/[REDACTED]/ExampleSDK.git) registered for path 'Samples/Example/Assets/ExampleSDK'
Cloning into '/bitrise/src/Samples/Example/Assets/ExampleSDK'...
```

**Comment by laco-dev** [comment]
I'll close this issue, thank you for answer 👍
