### ISSUE TITLE
Version 4.3.1 broke github checkout

### ISSUE THREAD

**Issue by will-nolan** [bitrise-steplib/steps-git-clone#151]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.3.1
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? Will investigate & report back

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description
Version 4.3.1 of checkout results in the error:

```
git "fetch" "--jobs=10" "origin" "refs/heads/dev"
error: unknown option `jobs=10'
```

When cloning a job from Github.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
git "fetch" "--jobs=10" "origin" "refs/heads/dev"
error: unknown option `jobs=10'
  </pre>
</details>

### Steps to reproduce

1. Attempt to clone project from Github
2. See that the project doesn't clone.

**Comment by jaspermeijaard** [comment]
We are facing the the same issue but I think this is introduced in version 4.3.1. I'm able to workaround this issue by checking out this step on version 4.3.0.

**Comment by juancarlosqr** [comment]
We are also facing a similar issue. I'm trying to trigger a manual build pointing to a specific commit hash and I specify the branch in "Advanced" but it still points to develop

`git "fetch" "origin" "refs/heads/develop"`

The problem is the commit hash is not found so the build fails

**Comment by will-nolan** [comment]
Can confirm @jaspermeijaard 

Just looked through our builds & 4.3.0 was working this morning. Looks like 4.3.1

**Comment by jaspermeijaard** [comment]
Before the step output, there's also a log printed that probably relates:
`Failed to download step.zip: Failed to download target from: https://bitrise-steplib-collection.s3.amazonaws.com/step-archives/git-clone/4.3.1/step.zip`

<details>
<summary>Log</summary>

```
Failed to download step.zip: Failed to download target from: https://bitrise-steplib-collection.s3.amazonaws.com/step-archives/git-clone/4.3.1/step.zip
+------------------------------------------------------------------------------+
| (2) git-clone                                                                |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 4.3.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-03-23T11:01:34Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- RepositoryURL: git@github.com:foo/bar.git
- CloneIntoDir: /bitrise/src
- Commit: foo-bar
- Tag: 
- Branch: foo
- PRDestBranch: 
- PRID: 0
- PRSourceRepositoryURL: 
- PRMergeBranch: 
- PRHeadBranch: 
- ResetRepository: false
- CloneDepth: 0
- LimitSubmoduleUpdateDepth: true
- ShouldMergePR: true
- BuildURL: https://app.bitrise.io/build/foo
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
$ git "init"
Initialized empty Git repository in /bitrise/src/.git/
$ git "remote" "add" "origin" "git@github.com:foo/bar.git"
$ git "fetch" "--jobs=10" "origin" "refs/heads/master"
error: unknown option `jobs=10'
usage: git fetch [<options>] [<repository> [<refspec>...]]
   or: git fetch [<options>] <group>
   or: git fetch --multiple [<options>] [(<repository> | <group>)...]
   or: git fetch --all [<options>]
```
</details>

**Comment by mateherber** [comment]
Hi @will-nolan,

Thanks for reporting this issue to us. We've released a new version of the step that contained a small performance improvement in several cases. However, it broke the step on our Ubuntu 16 LTS stack as it has a really old git version installed. We pulled the new version until we can update `git` on all our stacks to support this behaviour.

Please verify that your workflows no longer pick up the faulty `4.3.1` version and stays on `4.3.0`.

Thank you

**Comment by will-nolan** [comment]
Hey @mateherber 

I've launched a new build targetting 4.3.x & it's picking up 4.3.0, so everything's working again.

Thanks for the quick response.

:tada:
