### ISSUE TITLE
Version 4.3.x - 5.x:  manual PR merge chekout strategy can not be used: no source repository URL or source branch commit hash specified

### ISSUE THREAD

**Issue by JanC** [bitrise-steplib/steps-git-clone#155]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.x - 5.x
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO 

### Issue description
Hi,
my builds started to fail on the git clone phase without any changes from my side. The error message `ERROR: manual PR merge chekout strategy can not be used: no source repository URL or source branch commit hash specified` points to the file [checkout_method_pr_manual.go#L50-L52](https://github.com/bitrise-steplib/steps-git-clone/blob/master/gitclone/checkout_method_pr_manual.go#L50-L52).

In the logs (see below) the commit hash is indeed empty which is likely the reason for the failure. The question is how come the commit message is empty without any changes?

The build works fine if I downgrade to Git Clone `4.2.x` or lower!

### Bitrise info

- Build URL:  https://app.bitrise.io/build/e332bd5485997ae1#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES 
- Log: 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (1) git-clone@5.0                                                            |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 5.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-03-28T17:48:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- RepositoryURL: git@github.com:foo/ios-app.git
- CloneIntoDir: /Users/vagrant/git
- Commit: 
- Tag: 
- Branch: master
- PRDestBranch: master
- PRID: 0
- PRSourceRepositoryURL: 
- PRMergeBranch: 
- PRHeadBranch: 
- ResetRepository: false
- CloneDepth: 0
- FetchTags: false
- LimitSubmoduleUpdateDepth: true
- ShouldMergePR: true
- BuildURL: https://app.bitrise.io/build/e332bd5485997ae1
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
$ git "init"
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/vagrant/git/.git/
$ git "remote" "add" "origin" "git@github.com:pmtus/ios-app.git"
ERROR: manual PR merge chekout strategy can not be used: no source repository URL or source branch commit hash specified
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | git-clone@5.0 (exit code: 1)                                  | 5.59 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-git-clone/issues     |
| Source: https://github.com/bitrise-steplib/steps-git-clone                   |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

**Comment by lpusok** [comment]
Hello @JanC,
This behavior seems to be caused by manually overriding the branch_dest input of the git-clone step, this causes the Step to handle the build as a PR build, even if it is not one. Is there a specific reason to set this input?

```
    - git-clone@4.3:
        run_if: ".IsCI"
        inputs:
        - branch_dest: "$BITRISE_GIT_BRANCH"
```

**Comment by JanC** [comment]
hey @lpusok 

you are right, the parameter in my yml is causing the failure.

> Is there a specific reason to set this input?

Not really, I think it's a leftover from an old bitrise.yml. Thanks for your support. I'm closing the issue
