### ISSUE TITLE
Build step is using Tag object hash instead of Commit hash

### ISSUE THREAD

**Issue by Runman44** [bitrise-steplib/steps-git-clone#157]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 
**5.0.1**
- Is the issue reproducible with the latest version? **YES** / NO
- Does the issue happen sporadically, or every time? SPORADIC / **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / **NOT APPLICABLE**

### Issue description

It seems when pushing a tag - this buildstep is using the hash of the tag itself instead of the hash of the commit it tagged to! 

**TAG OBJECT HASH**
 git show-ref --tags
 e06528dc9487b4946fc5fec9c6f0e2f9de7f1604 refs/tags/6.8.0

**SHA1 hash of the commit, instead of the tag object**
git show-ref --tags -d
e06528dc9487b4946fc5fec9c6f0e2f9de7f1604 refs/tags/6.8.0
44130545fd679239d723a808ffde936bb7ee2b00 refs/tags/6.8.0^{}

see also: https://stackoverflow.com/questions/8796522/git-tag-list-display-commit-sha1-hashes

### Bitrise info

<details>
  <pre>
Config:
- RepositoryURL: XXXXX
- CloneIntoDir: /bitrise/src
- Commit: e06528dc9487b4946fc5fec9c6f0e2f9de7f1604
- Tag: 6.8.0
- Branch: 
- PRDestBranch: 
- PRID: 0
- PRSourceRepositoryURL: 
- PRMergeBranch: 
- PRHeadBranch: 
- ResetRepository: false
- CloneDepth: 0
- FetchTags: false
- LimitSubmoduleUpdateDepth: true
- ShouldMergePR: true
- BuildURL: https://app.bitrise.io/build/5b483decb63a3bab
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true

$ git "checkout" "e06528dc9487b4946fc5fec9c6f0e2f9de7f1604"
fatal: reference is not a tree: e06528dc9487b4946fc5fec9c6f0e2f9de7f1604
Checkout strategy used: gitclone.checkoutCommit
ERROR: checkout failed (e06528dc9487b4946fc5fec9c6f0e2f9de7f1604): fatal: reference is not a tree: e06528dc9487b4946fc5fec9c6f0e2f9de7f1604
  </pre>
</details>

### How to fix

Please use the commit hash instead of the tag object

**Comment by andtie** [comment]
FWIW: I got the described behaviour and the error message `fatal: reference is not a tree`. I looked into the recent releases and saw that fetching tags is now disabled by default (see https://github.com/bitrise-steplib/steps-git-clone/releases/tag/5.0.0). After reenabling it, the problem disappeared for me.
