### ISSUE TITLE
Error after updating  git-clone step to 6.1.0

### ISSUE THREAD

**Issue by Drevil5** [bitrise-steplib/steps-git-clone#166]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 6.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled:  NO
- Log: 

Rollback to version 6.0 solves the problem

**Comment by cathyharmon** [comment]
Hello,

What stack were you running on? The new git-clone version 6.1.0 is not compatible with LTS Ubuntu 16.  You should either continue to run with the 6.0.0 version of the step, or move the Ubuntu 20 stack.  

If you are using Ubuntu 16 stack, please be aware that Ubuntu 16 stack will no longer be available after August 27, 2021.  We strongly recommend moving to Ubuntu 20 stack now.
