### ISSUE TITLE
Git clone hangs on `Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.`

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [bitrise-steplib/steps-git-clone#176]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions. YES
- Which version of the step is effected? 6.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The issue is similar to [Issue 131](https://github.com/bitrise-steplib/steps-git-clone/issues/131)

### Bitrise info

- Build URL: 
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

```
$ git "fetch" "--jobs=10" "--no-tags" "origin" "refs/heads/develop"
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
timeout after 5400 seconds
```
<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by shams-ahmed** [comment]
@GermanVelibekovHouzz hard to say what this could be without more information.. have you checked the auth? try different test repo or branch. 

also, look into the config options, one option might be to limit fetch to one commit.

**Comment by GermanVelibekovHouzz** [comment]
@shams-ahmed Thanks for your reply. I checked it on several branches and for two Bitrise apps with SSH keys configured differently. The result is the same. 

Where should I look for that config option with the one commit fetch?

**Comment by GermanVelibekovHouzz** [comment]
I added a build URL and enabled Bitrise Support.

**Comment by GermanVelibekovHouzz** [comment]
Limiting the fetch did the trick! @shams-ahmed thanks again

**Comment by shams-ahmed** [comment]
Nice!.. also try looking at how much disk space your branch is using with `git rev-list`
https://github.com/git/git/blob/6fe12b5215f4ca597accc97ac5dce0f88e8483e9/Documentation/c#L86
