### ISSUE TITLE
Error on 8.x.x - fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by pedrosilva88** [bitrise-steplib/steps-git-clone#211]
### Troubleshooting

- [✅] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 8.x.x
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Since I started using the git-clone version 8.x.x my scripts started to showing me this error message: "fatal: refusing to merge unrelated histories", when I'm trying to do a merge to the master branch.

If I change the git-clone version to 7.x.x or below, it works fine.

### Bitrise info

- Build URL: [iOS build](https://app.bitrise.io/app/8b09dec6016ed2a8)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log:
<details>
  <pre>
[18:56:28]: $ .././release_finish.py -b
[18:56:28]: ▸ HEAD is now at a9b4df8 *****
[18:56:28]: ▸ HEAD is now at a9b4df8 *****
[18:56:28]: ▸ Previous HEAD position was a9b4df8 *****
[18:56:28]: ▸ Switched to branch 'release-*****'
[18:56:28]: ▸ Your branch is up to date with 'origin/release-*****'.
[18:56:28]: ▸ Switched to a new branch 'master'
[18:56:28]: ▸ branch 'master' set up to track 'origin/master'.
[18:56:29]: ▸ Warning: Permanently added 'gitlab.com' (*****) to the list of known hosts.
[18:56:29]: ▸ Already up to date.
[18:56:29]: ▸ fatal: refusing to merge unrelated histories
  </pre>
</details>

### Steps to reproduce
This happens when I create a release branch from develop, then I do a commit and push on this release branch. After that I merge into develop and when I'm going to merge this into Master I receive this error message.

I believe if we create a new Workflow with these steps(using different branches) we might have the same error. I don't want to run this particular one because this is the Workflow that sends a new Build to AppStore.

**Comment by BitRaisa** [comment]
Hi @pedrosilva88 , could you try setting the **Clone depth** under the **Clone options** to `1000` and rebuild? Let us know how it goes! :)

**Comment by pedrosilva88** [comment]
It's working for now. Closing the issue, thanks for the support.
