### ISSUE TITLE
`$GIT_CLONE_COMMIT_COUNT` is 1 as default

### ISSUE THREAD

**Issue by MortenGregersen** [bitrise-steplib/steps-git-clone#215]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? **8.1.1**
- Is the issue reproducible with the latest version? **YES**
- Does the issue happen sporadically, or every time? **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? **NOT APPLICABLE**

### Issue description

When I upgraded to 8.x.x (from 6.x.x) the variable `$GIT_CLONE_COMMIT_COUNT` always return 1. I understand that this is a consequence of using shallow cloning (https://discuss.bitrise.io/t/git-clone-commit-count-returns-1-instead-of-actual-commit-count/22461), but shouldn't this variable still contain the total number of commits on the branch? It is still possible to get the total number of commits (https://stackoverflow.com/questions/677436/how-do-i-get-the-git-commit-count)

### Steps to reproduce

1. Upgrade to version 8.x.x (`git-clone@8: {}`)
2. Use the `$GIT_CLONE_COMMIT_COUNT` in another step

**Comment by i0SFrank** [comment]
Git clone Repository (Failed)
