### ISSUE TITLE
Error with version 8.2.1

### ISSUE THREAD

**Issue by fcar12** [bitrise-steplib/steps-git-clone#221]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 8.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Hello,
I'm still analysing further but it seems that when my workflows started using the latest 8.2.1 version earlier today (auto-update), ALL of them started failing.

I've rolled back to 8.0.1 and it's working fine.
Note: using bitbucket self-hosted.

Hope this helps!
Cheers,
Francisco
### Bitrise info

- Build URL: https://app.bitrise.io/build/41c38d56-10f5-4941-8c9c-1dc2ea392eb5
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
Working tree is dirty, cleaning before checkout:
$ git "clean" "-fd"
...
$ git "reset" "--hard" "HEAD"
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Failed to reset repository: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
$ git "fetch" "--jobs=10" "--no-tags" "origin" "refs/heads/develop"
fatal: refusing to work with credential missing host field
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by fcar12** [comment]
Additional info as I think I determined the cause for the problem:

1. As we are using self hosted bitbucket, prior to cloning the repo we configure authentication with netrc and download all the required crts and keys.
2. This is causing the repo not to be clean and failing the check introduced in this new 8.2.1 version
3. After determine it's not clean, git clean -fd deletes everything
4. Authentication fails when doing the hard reset as there is no GIT_HTTP_USERNAME and GIT_HTTP_PASSWORD configured.

Is this expected? Should we change the way we do authentication to use the experimental support introduced in 8.1.0?

**Comment by fcar12** [comment]
Update: if I try to use this step authentication (removed other steps prior to this), the clean check passes but then authentication doesn't work:

```shell
$ git "fetch" "--jobs=10" "--depth=1" "--no-tags" "origin" "refs/heads/develop"
fatal: unable to access ... LibreSSL SSL_read: error:1404C45C:SSL routines:ST_OK:reason(1116), errno 0
```

**Comment by ofalvai** [comment]
Oh, you are right @fcar12, the root cause is that the working directory has a new file added prior to running the git clone step (and the file is needed for the git clone to work).
Would it be possible to download the required files to another dir, for example the home dir? This way, the working directory (`$BITRISE_SOURCE_DIR`) would remain clean.

**Comment by fcar12** [comment]
@ofalvai, writing the files to the home dir instead does work (although it requires further changes in the workflows, to other steps that also require the same files for updating git status).

However, we could avoid this (having extra steps and files, which would also be good) if the authentication support for private http repositories was working correctly (see comment above). Should I file a ticket for that or as it is experimental, you are already aware of this and it should be working correctly in a future release?
