### ISSUE TITLE
Build triggered by branch push doesn't check out that branch

### ISSUE THREAD

**Issue by ericvan76** [bitrise-steplib/steps-git-clone#46]
This is a log triggered by a branch push, on v3.5.3
```
Git Clone Configs:
- CloneIntoDir: /Users/vagrant/git
- RepositoryURL: git@github.com:someone/somerepo.git
- UpdateSubmodules: yes
Git Checkout Configs:
- Commit: 4a922f529f38a3e6b75d5a8cd0f1f3778c026542
- Tag: 
- Branch: master
- CloneDepth: 
Git Pull Request Configs:
- PullRequestURI: 
- PullRequestID: 
- BranchDest: 
- PullRequestMergeBranch: 
- ResetRepository: No
Bitrise Build Configs:
- BuildURL: https://www.bitrise.io/build/xxx
- BuildAPIToken: xxx
Git clone repository
=> git "init"
=> git "remote" "add" "origin" "git@github.com:someone/somerepo.git"
=> git "fetch"
=> git "checkout" "4a922f529f38a3e6b75d5a8cd0f1f3778c026542"
=> git "submodule" "update" "--init" "--recursive"
```

`git "checkout" "4a922f529f38a3e6b75d5a8cd0f1f3778c026542"` should be something like
`git "checkout" -b "master" "4a922f529f38a3e6b75d5a8cd0f1f3778c026542"`

It doesn't make any sense not checking out the *branch* if the build is triggered by a *branch* push.

**Comment by viktorbenei** [comment]
Hi @ericvan76 ,

What would `git "checkout" -b "master" "4a922f529f38a3e6b75d5a8cd0f1f3778c026542"` do differently? 

We do a checkout on the commit hash directly because if in the meantime you'd push a new commit to master then the build would not test the commit it states it tests. Furthermore checking out the commit directly makes it possible to re-build previous builds / previous git commits.

**Comment by ericvan76** [comment]
No, with the commit id you can still re-build the previous builds/commits, check-out a branch on a previous commit is absolutely okay. Basically without any repo change, Push-trigger and further x times Manual-triggers shouldn't have anything different in that repo, including the local branch ref, which is important! Because other steps may need it. The only difference here is the push-triggered build carries the commit id, which allows you to check-out the same commit when rebuild.

**Comment by viktorbenei** [comment]
Yes, and it's exactly how it works right now - if a commit hash is defined we checkout the commit hash. If you do e.g. a manual build and you *don't* specify a commit hash then this step will checkout the branch instead.

Just tried the change you suggested, to do `git checkout -b BRANCH COMMIT_HASH` and it doesn't seem to work:

```
git checkout -b master e2f3ac967d9b6907f6e2517de37344f2085900ef
fatal: A branch named 'master' already exists.
```

While git checkout COMMIT works:

```
git checkout e2f3ac967d9b6907f6e2517de37344f2085900ef
Note: checking out 'e2f3ac967d9b6907f6e2517de37344f2085900ef'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e2f3ac9... auto-test
```

**Comment by ericvan76** [comment]
When you see
“fatal: A branch named 'master' already exists.”, you must run that command locally or a manual branch triggered build.

But in a push triggered build, there is no master branch, because you check out the commit as HEAD.

If you want to test it locally, just delete your local master branch and try again. See how it happens.

That’s exactly what I’m talking about.

And just be open minded please, this is a very first step of a build job. And checkout is not only for “get something from repo and build it”. There is so many other scenarios user may need to do over it. Inconsistent local branch between manual and push actually break things. You may not be able to see it, but I do. It’s hard to explain what I’m trying to do. But in gene user can easily trigger a new build instead of rebuild. But they got different branch.

Just a bit funny if we say a build is triggered by a branch push, but after check out you’re not on that branch. Isn’t it?

Anyway, it’s just a suggestion. I can work around with it. Of course I can always work around with bash script even without this step, but that’s not why I’m talking here. I’m just trying to correct things.

Eric

**Comment by viktorbenei** [comment]
Sure, don't get me wrong @ericvan76 , your feedback is very much appreciated!

I guess what I meant to ask: what's your use case where the current version of the step is not appropriate? Is there an issue caused by `git checkout COMMIT-HASH`?

**Comment by ericvan76** [comment]
Try GitVersion. 

GitVersion uses branch-names/tags to calculate SemVer, it won't work properly with `git checkout 'COMMIT'`.

**Comment by viktorbenei** [comment]
That's a great point! Thanks for the feedback! :)

A revision for this step is already schedule (can't commit to any date yet), will add this feature request to the scope of that task :)

**Comment by ericvan76** [comment]
Thanks, that’s great. Just like what I said I can easily work around, not necessary to be a high priority.

Eric

**Comment by viktorbenei** [comment]
Thanks @ericvan76 ! :)

**Comment by matkoch** [comment]
Any progress?

**Comment by ericvan76** [comment]
@matkoch, not yet I think. I'm currently doing a workaround in GitVersion.yml. I can help if this breaks your semver generation in GitVersion.

**Comment by viktorbenei** [comment]
@matkoch our recommended solution is that if you need the tags for any tool please ensure that those are available, by running `git fetch --tags` or similar yourself, before you'd use the tags.

**Comment by viktorbenei** [comment]
@matkoch just deleted my previous comment, sorry, wrong thread :P

**Comment by matkoch** [comment]
I think the only workaround currently is execute `git checkout -b %BITRISE_GIT_BRANCH%`, am I right?

**Comment by ericvan76** [comment]
@matkoch, in my scenario, I included both local and remote branch names in GitVersion.yml to get it working.
