### ISSUE TITLE
4.0.10 stopped fetching tags for PRs

### ISSUE THREAD

**Issue by ansman** [bitrise-steplib/steps-git-clone#78]
Our build figures out the version name by using `git describe` and as of 4.0.10 it stopped fetching tags (for PRs at least) which causes `git describe` to fail. It would be great if it could either fetch tags automatically or if there could be an option for always fetching them.

For now we're using 4.0.9 which works just fine.

**Comment by viktorbenei** [comment]
Thanks for reporting @ansman and sorry for the inconvenience! Created an internal issue report and linked this one.

**Comment by ansman** [comment]
No worries, it caused very little inconvenience and using the previous version was easy enough.

**Comment by viktorbenei** [comment]
Glad to hear :) We'll discuss a long term solution, to provide options for those who need more git history as well as to those who need maximum optimization (fetch as little as possible).

**Comment by powdahound** [comment]
Ran into this issue as well. We are also using `git describe` to look for a tag that indicates a version number to use for the build. Being able to pass `--tags` to the `git fetch origin <branch>` command in the clone step would work for our case.

**Comment by kdobmayer** [comment]
The git clone step's responsibility is to get the source code. The `git describe` command relies on the fact that the most recent tag related to HEAD is there. Fetching all tags by default would fetch unnecessary refs resulting slower step execution for everybody who doesn't want to do anything with the tags just want to test the source code (which was the case before version 4.0.10).
I think we should consider to add an option for always fetch tags, but disable it by default.

I recommend to use the latest version of the step, because it can be much faster and then use the following command to get the version number:
```
git fetch --tags origin "$BITRISE_GIT_BRANCH" && git describe
```

**Comment by viktorbenei** [comment]
Thanks for the explanation @kdobmayer !

@ansman & @powdahound : do you use `git describe` in your own scripts, where you can add the suggested `git fetch --tags origin "$BITRISE_GIT_BRANCH" && git describe` (or `git fetch --tags && git describe`), or do you need that for a specific tool?

**Comment by motorro** [comment]
Hi!
@viktorbenei, 
I'm affected also.
If I get you right you propose put it to gradle script (Android in my case). If I put it there the fetch command will fire every time the build is requested (even local build).
The separate gradle task is a way out here but putting it to project gradle seems a bit hardcode for bitrise :)

**Comment by viktorbenei** [comment]
@motorro thanks for the info! The suggested solution can be added as a Script step, e.g. right after the Git Clone step, with just `git fetch --tags`.

Adding it to the gradle task might still be a good idea though, to ensure that it works with up to date tags infos when you run `git describe`.

**Comment by ansman** [comment]
Well, I think you can put it as a build step. But it will increase the build time more than if clone synced them.

**Comment by viktorbenei** [comment]
Are you sure @ansman ? I don't think there's a significant difference, but I might be wrong.

**Comment by viktorbenei** [comment]
@ansman can you check the difference, v4.0.9 vs v4.0.10 + `git fetch --tags` script

**Comment by motorro** [comment]
@viktorbenei I'm ok with the extra step then.

**Comment by powdahound** [comment]
@viktorbenei Yes, we are doing this in our own script so calling `git fetch --tags` there is not an issue. 👍

**Comment by spacemase** [comment]
We are affected by this as well.  Testing v4.0.9 to confirm and then will explore pairing that with `git describe` in our build.gradle.  Note we are now using the option to set clone depth to 1000 (logs indicate depth is now 0) to maintain performance, but require the history for the describe command.

**Comment by spacemase** [comment]
v4.0.9 works again for us, though it clones entire commit history so understand its undesirability.  We find pairing `git fetch --tags` with `git describe` to be undesirable as well, as fetch may have undesirable side effects on individual dev machines that prune branches aggressively.  Would prefer this behavior be confined to the CI/CD space as an option to prevent side effects.

**Comment by kdobmayer** [comment]
`git fetch --tags`fetches all branches, which can be slow, but `git fetch --tags origin <branch>` fetches only the tags, because the affected branch is already fetched by the git clone step.

An other workaround can be to get the latest tag from API. It's not as short as `git describe`, but it's more reliable, because working without even cloning the repository. In case of GitHub:
```
curl -fsSL https://api.github.com/repos/<owner>/<repository>/tags | jq -r '.[0].name'
```
If the tags are not using semantic versioning, the `jq` part is a little bit more complicated (in case of self hosted Git servers, or GitLab, Bitbucket, etc. the API url differs).

The most user-friendly solution is to add an additional option for the git clone step to fetch all tags, but if a project relies heavily on scripts I would recommend a more sophisticated solution to get the latest version than `git describe`.

**Comment by spacemase** [comment]
@kdobmayer @viktorbenei omg thank you so much!  This is a great pointer, Hadn't look at it in some time, but yes the `describe` command was a poor hack to begin with.  

 I can produce something much more concise now.  An option for the git clone step is unnecessary.

Thank you!

**Comment by viktorbenei** [comment]
Glad to hear & thanks for the feedback @spacemase ! ;)

**Comment by viktorbenei** [comment]
Thanks for the benchmark @ansman !
The thing is, you did not measure one more thing, how much it takes to not to fetch the tags at all, as that's the most common use case.

E.g. when you're doing a pull request build you most likely won't need the tags at all. So even if for a release build it will add some time (how much depends on the number of tags) you save more time during the PR builds.

**Comment by viktorbenei** [comment]
Also, for:

> Since my repo is quite small the actual time difference isn't that large but in % it's quite a bit slower.

I wouldn't compare it in %, as quite a bit of the time is the network communication here, so it's more like "it adds a couple of seconds" vs +50%

**Comment by ansman** [comment]
The time to fetch tags were 1.56s, 1.36s and 1.28s respectively with an average of 1.4s

**Comment by ansman** [comment]
I agree, but regardless I would like an option to allow fetching tags in a single step

**Comment by viktorbenei** [comment]
Definitely see your point @ansman , I'll keep this ticket open & discuss it with the team!

**Comment by pres** [comment]
I also stumbled into this issue. 
I reverted to using 4.0.9 of the git clone step. 
An option to get the tags would be appreciated!

**Comment by viktorbenei** [comment]
Is there a reason why you don't want to add a script with e.g. `git fetch --tags` @pres ?

**Comment by paymand** [comment]
@viktorbenei: I ran into the same bug today. For now I worked around it by adding the script you mentioned above to **all** my workflows. Would be nice to get it fixed.

**Comment by viktorbenei** [comment]
@paymand it's in our backlog to add an option to the step. In either case you'd have to do that for every workflow if you have git clone in separate workflows.

The best solution for this is to use a common workflow and have it as a `before_run` workflow in all workflows, so you don't have to repeat the same setup code. Something like this:

```
workflows:

  _setup:
    steps:
    - git-clone: {}
    - script: {} // to fetch the tags

  primary:
    before_run:
    - _setup
    steps: []

  deploy:
    before_run:
    - _setup
    steps: []
```

"Workflow chaining" docs: https://devcenter.bitrise.io/bitrise-cli/workflows/#chaining-workflows-and-reusing-workflows
