### ISSUE TITLE
Git clone without automerge 

### ISSUE THREAD

**Issue by VictorAlbertos** [bitrise-steplib/steps-git-clone#90]
Is there a way to perform a `git-clone` without doing `automerge`? I get this error when the target branch has merge conflicts with master, and the build stops right away, I would like to know if it's possible to avoid `automerge` and let the build continue.

```
CONFLICT (content): Merge conflict in android-test-commons/src/main/java/com/cookpad/android/test/commons/runner/setup/Setup.kt
Automatic merge failed; fix conflicts and then commit the result.
```

Thanks.

**Comment by godrei** [comment]
Hi @VictorAlbertos ,

In case of Pull Request triggered build, we merge the PR source branch to the PR destination branch, to run the automation against the project state, which would be after merging the PR. This way you can validate if merging the PR will break anything or not.

If you do not need this validation, then you can opt-out PR triggered builds: https://devcenter.bitrise.io/builds/triggering-builds/trigger-map/ and use only PUSH triggers.

Am I missing something?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @VictorAlbertos please let us know if we can help with anything by opening a new issue!
