### ISSUE TITLE
Error "Server does not allow request for unadvertised object" when using 4.0.10

### ISSUE THREAD

**Issue by eric-PearSports** [bitrise-steplib/steps-git-clone#95]
when I switch from version 4.0.9, to 4.0.10, I get the following error when calling 'git fetch --tags': 
Server does not allow request for unadvertised object xxxxx

any idea?

**Comment by bitce** [comment]
Hi @eric-PearSports!

Could you please paste the related build's URL here?

**Comment by godrei** [comment]
Closing as we did not receive a reply - @eric-PearSports  please let us know if we can help with anything by opening a new issue!
