### ISSUE TITLE
trim message body to 72 characters 

### ISSUE THREAD

**Issue by kveldkamp** [bitrise-steplib/steps-git-clone#97]
I use the message body for tracking what gets sent out to fabric builds, and was wondering why it kept cutting off short recently.  

It appears 4.0.15 introduced something around content trimming to 72 characters. I was wondering if instead of that being default, it could be added as an option in a future release.

**Comment by ahvth-bitrise** [comment]
Hi @kveldkamp , we are currently trimming commit messages to 72 characters to avoid exceeding the maximum number of characters that can be added to an environment variable. The next release will perform the commit message trimming dynamically according to the current evironment variable character limit (which should definitely be more than 72 characters 😄 ).
